# Generated by Django 5.0.4 on 2024-05-02 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0008_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalPerformance',
            new_name='PerformanceRecord',
        ),
    ]
