# Generated by Django 5.0.4 on 2024-05-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0009_rename_historicalperformance_performancerecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerformanceRecord',
        ),
    ]
