# Generated by Django 5.0.4 on 2024-05-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0012_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='issues',
            field=models.TextField(blank=True, null=True),
        ),
    ]
